/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
/* tslint:disable */
export var styles = ['.card[_ngcontent-%COMP%] {\r\n}\r\n\r\n.card[_ngcontent-%COMP%]   .front[_ngcontent-%COMP%] {\r\n}\r\n\r\n.card[_ngcontent-%COMP%]   .back[_ngcontent-%COMP%] {\r\n}\r\n\r\n.card[_ngcontent-%COMP%]   div.carousel-caption[_ngcontent-%COMP%] {\r\n    top: auto;\r\n    bottom: 0;\r\n    padding-top: 0;\r\n    padding-bottom: 0;\r\n    background-color: black;\r\n    \r\n    opacity: 0.3;\r\n    width: 100%;\r\n    left: 0;\r\n    right: 0;\r\n    font-weight: bold;\r\n    \r\n}'];
//# sourceMappingURL=grid-memory.component.css.shim.js.map