/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/GridMemory/grid-memory.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../../app/GridMemory/grid-memory.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './grid-memory.component.css.shim';
import * as import13 from '../spinner/my-spinner.component.ngfactory';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '../../../app/spinner/my-spinner.component';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import20 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/common/src/directives/ng_class';
import * as import23 from '@angular/core/src/security';
export class Wrapper_GridMemoryComponent {
  context:import0.GridMemoryComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.GridMemoryComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_GridMemoryComponent_Host:import2.RenderComponentType = (null as any);
class _View_GridMemoryComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _GridMemoryService_0_4:import4.GridMemoryService;
  _GridMemoryComponent_0_5:Wrapper_GridMemoryComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_GridMemoryComponent_Host0,renderType_GridMemoryComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'my-grid-memory',import5.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_GridMemoryComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._GridMemoryService_0_4 = new import4.GridMemoryService(this.parentInjector.get(import9.Http));
    this._GridMemoryComponent_0_5 = new Wrapper_GridMemoryComponent(this._GridMemoryService_0_4);
    this._appEl_0.initComponent(this._GridMemoryComponent_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._GridMemoryComponent_0_5.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.GridMemoryService) && (0 === requestNodeIndex))) { return this._GridMemoryService_0_4; }
    if (((token === import0.GridMemoryComponent) && (0 === requestNodeIndex))) { return this._GridMemoryComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._GridMemoryComponent_0_5.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._GridMemoryComponent_0_5.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_GridMemoryComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_GridMemoryComponent_Host === (null as any))) { (renderType_GridMemoryComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_GridMemoryComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const GridMemoryComponentNgFactory:import11.ComponentFactory<import0.GridMemoryComponent> = new import11.ComponentFactory<import0.GridMemoryComponent>('my-grid-memory',viewFactory_GridMemoryComponent_Host0,import0.GridMemoryComponent);
const styles_GridMemoryComponent:any[] = [import12.styles];
var renderType_GridMemoryComponent:import2.RenderComponentType = (null as any);
class _View_GridMemoryComponent0 extends import1.AppView<import0.GridMemoryComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _MySpinner_35_4:import13.Wrapper_MySpinner;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _MySpinner_37_4:import13.Wrapper_MySpinner;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _TemplateRef_43_5:any;
  _NgFor_43_6:import14.Wrapper_NgFor;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_GridMemoryComponent0,renderType_GridMemoryComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
    this._expr_53 = import8.UNINITIALIZED;
    this._expr_54 = import8.UNINITIALIZED;
    this._expr_55 = import8.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray4(4,'class','row','id','gridMenu'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'div',new import5.InlineArray2(2,'class','btn-toolbar memGrid'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_4,'div',new import5.InlineArray4(4,'class','btn-group','role','group'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_6,'span',new import5.InlineArray2(2,'class','navbar-brand'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_12 = import5.createRenderElement(this.renderer,this._el_4,'div',new import5.InlineArray4(4,'class','btn-group pull-right','role','group'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n				',(null as any));
    this._el_14 = import5.createRenderElement(this.renderer,this._el_12,'button',new import5.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_16 = import5.createRenderElement(this.renderer,this._el_14,'span',new import5.InlineArray2(2,'class','glyphicon glyphicon-refresh'),(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n			',(null as any));
    this._text_19 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_20 = import5.createRenderElement(this.renderer,this._el_4,'div',new import5.InlineArray4(4,'class','btn-group pull-right','role','group'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n				',(null as any));
    this._el_22 = import5.createRenderElement(this.renderer,this._el_20,'button',new import5.InlineArray2(2,'class','btn btn-success disabled'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n                    ',(null as any));
    this._el_24 = import5.createRenderElement(this.renderer,this._el_22,'span',new import5.InlineArray2(2,'class','label label-success badge'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_20,'\n				',(null as any));
    this._el_28 = import5.createRenderElement(this.renderer,this._el_20,'button',new import5.InlineArray2(2,'class','btn btn-danger disabled'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._el_30 = import5.createRenderElement(this.renderer,this._el_28,'span',new import5.InlineArray2(2,'class','label label-danger badge'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_20,'\n			',(null as any));
    this._text_34 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_35 = import5.createRenderElement(this.renderer,this._el_4,'my-spinner',new import5.InlineArray2(2,'bdgClass','glyphicon-th'),(null as any));
    this._appEl_35 = new import3.AppElement(35,4,this,this._el_35);
    var compView_35:any = import13.viewFactory_MySpinner0(this.viewUtils,this.injector(35),this._appEl_35);
    this._MySpinner_35_4 = new import13.Wrapper_MySpinner();
    this._appEl_35.initComponent(this._MySpinner_35_4.context,([] as any[]),compView_35);
    compView_35.create(this._MySpinner_35_4.context,([] as any[]),(null as any));
    this._text_36 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_37 = import5.createRenderElement(this.renderer,this._el_4,'my-spinner',new import5.InlineArray2(2,'bdgClass','glyphicon-time'),(null as any));
    this._appEl_37 = new import3.AppElement(37,4,this,this._el_37);
    var compView_37:any = import13.viewFactory_MySpinner0(this.viewUtils,this.injector(37),this._appEl_37);
    this._MySpinner_37_4 = new import13.Wrapper_MySpinner();
    this._appEl_37.initComponent(this._MySpinner_37_4.context,([] as any[]),compView_37);
    compView_37.create(this._MySpinner_37_4.context,([] as any[]),(null as any));
    this._text_38 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_39 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_41 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray4(4,'class','row','style','text-align: center;'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n		',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor(this._el_41,(null as any));
    this._appEl_43 = new import3.AppElement(43,41,this,this._anchor_43);
    this._TemplateRef_43_5 = new import15.TemplateRef_(this._appEl_43,viewFactory_GridMemoryComponent1);
    this._NgFor_43_6 = new import14.Wrapper_NgFor(this._appEl_43.vcRef,this._TemplateRef_43_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_44 = this.renderer.createText(this._el_41,'\n	',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_35,'counterChange',this.eventHandler(this._handle_counterChange_35_0.bind(this)));
    const subscription_0:any = this._MySpinner_35_4.context.counterChange.subscribe(this.eventHandler(this._handle_counterChange_35_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_37,'counterChange',this.eventHandler(this._handle_counterChange_37_0.bind(this)));
    const subscription_1:any = this._MySpinner_37_4.context.counterChange.subscribe(this.eventHandler(this._handle_counterChange_37_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MySpinner) && (35 === requestNodeIndex))) { return this._MySpinner_35_4.context; }
    if (((token === import17.MySpinner) && (37 === requestNodeIndex))) { return this._MySpinner_37_4.context; }
    if (((token === import15.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import18.NgFor) && (43 === requestNodeIndex))) { return this._NgFor_43_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_35_0_0:any = this.context.limit;
    this._MySpinner_35_4.check_counterValue(currVal_35_0_0,throwOnChange,false);
    const currVal_35_0_1:any = 'glyphicon-th';
    this._MySpinner_35_4.check_bdgClass(currVal_35_0_1,throwOnChange,false);
    this._MySpinner_35_4.detectChangesInInputProps(this,this._el_35,throwOnChange);
    const currVal_37_0_0:any = this.context.seconds;
    this._MySpinner_37_4.check_counterValue(currVal_37_0_0,throwOnChange,false);
    const currVal_37_0_1:any = 'glyphicon-time';
    this._MySpinner_37_4.check_bdgClass(currVal_37_0_1,throwOnChange,false);
    this._MySpinner_37_4.detectChangesInInputProps(this,this._el_37,throwOnChange);
    const currVal_43_0_0:any = this.context.files;
    this._NgFor_43_6.check_ngForOf(currVal_43_0_0,throwOnChange,false);
    this._NgFor_43_6.detectChangesInInputProps(this,this._anchor_43,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_53:any = import5.interpolate(1,'',this.context.question,'');
    if (import5.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setText(this._text_9,currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = import5.interpolate(1,'',this.context.countSuc,'');
    if (import5.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setText(this._text_25,currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = import5.interpolate(1,'',this.context.countErr,'');
    if (import5.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setText(this._text_31,currVal_55);
      this._expr_55 = currVal_55;
    }
    this._MySpinner_35_4.detectChangesInHostProps(this,this._el_35,throwOnChange);
    this._MySpinner_37_4.detectChangesInHostProps(this,this._el_37,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>this.context.onClickReload()) !== false);
    return (true && pd_14_0);
  }
  private _handle_counterChange_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_35_0:any = ((<any>this.context.onChangeLimit($event)) !== false);
    return (true && pd_35_0);
  }
  private _handle_counterChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_37_0:any = ((<any>this.context.onChangeTimeout($event)) !== false);
    return (true && pd_37_0);
  }
}
export function viewFactory_GridMemoryComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.GridMemoryComponent> {
  if ((renderType_GridMemoryComponent === (null as any))) { (renderType_GridMemoryComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_GridMemoryComponent,{})); }
  return new _View_GridMemoryComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_GridMemoryComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import19.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import19.Wrapper_NgClass;
  _text_3:any;
  _el_4:any;
  _NgClass_4_3:import19.Wrapper_NgClass;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _NgClass_13_3:import19.Wrapper_NgClass;
  _text_14:any;
  _el_15:any;
  _NgClass_15_3:import19.Wrapper_NgClass;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _map_26:any;
  _map_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  _map_32:any;
  _map_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_GridMemoryComponent1,renderType_GridMemoryComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
    this._map_26 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {hidden: p0};
    });
    this._map_27 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._map_32 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {hidden: p0};
    });
    this._map_33 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_34 = import8.UNINITIALIZED;
    this._expr_35 = import8.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.createRenderElement(this.renderer,(null as any),'div',new import5.InlineArray4(4,'class','carousel slide card','data-ride','carousel'),(null as any));
    this._NgClass_0_3 = new import19.Wrapper_NgClass(this.parent.parentInjector.get(import16.IterableDiffers),this.parent.parentInjector.get(import20.KeyValueDiffers),new import21.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray4(4,'class','carousel-inner  img-thumbnail face front','role','listbox'),(null as any));
    this._NgClass_2_3 = new import19.Wrapper_NgClass(this.parent.parentInjector.get(import16.IterableDiffers),this.parent.parentInjector.get(import20.KeyValueDiffers),new import21.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'div',new import5.InlineArray2(2,'class','item'),(null as any));
    this._NgClass_4_3 = new import19.Wrapper_NgClass(this.parent.parentInjector.get(import16.IterableDiffers),this.parent.parentInjector.get(import20.KeyValueDiffers),new import21.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_4,'img',new import5.InlineArray2(2,'class','img-responsive'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_4,'div',new import5.InlineArray2(2,'class','carousel-caption'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_13 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray2(2,'class','carousel-inner img-thumbnail face back'),(null as any));
    this._NgClass_13_3 = new import19.Wrapper_NgClass(this.parent.parentInjector.get(import16.IterableDiffers),this.parent.parentInjector.get(import20.KeyValueDiffers),new import21.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n				',(null as any));
    this._el_15 = import5.createRenderElement(this.renderer,this._el_13,'div',new import5.InlineArray2(2,'class','item'),(null as any));
    this._NgClass_15_3 = new import19.Wrapper_NgClass(this.parent.parentInjector.get(import16.IterableDiffers),this.parent.parentInjector.get(import20.KeyValueDiffers),new import21.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText(this._el_15,'\n					',(null as any));
    this._el_17 = import5.createRenderElement(this.renderer,this._el_15,'img',new import5.InlineArray4(4,'class','img-responsive','src','/components/cover.jpg'),(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n				',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n			',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n		',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.NgClass) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._NgClass_4_3.context; }
    if (((token === import22.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgClass_2_3.context; }
    if (((token === import22.NgClass) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgClass_15_3.context; }
    if (((token === import22.NgClass) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_13_3.context; }
    if (((token === import22.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'carousel slide card';
    this._NgClass_0_3.check_klass(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parent.context.cardClasses;
    this._NgClass_0_3.check_ngClass(currVal_0_0_1,throwOnChange,false);
    this._NgClass_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = 'carousel-inner  img-thumbnail face front';
    this._NgClass_2_3.check_klass(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = this._map_26(!this.context.$implicit.isFront);
    this._NgClass_2_3.check_ngClass(currVal_2_0_1,throwOnChange,false);
    this._NgClass_2_3.detectChangesInInputProps(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = 'item';
    this._NgClass_4_3.check_klass(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = this._map_27(this.context.$implicit.isFront);
    this._NgClass_4_3.check_ngClass(currVal_4_0_1,throwOnChange,false);
    this._NgClass_4_3.detectChangesInInputProps(this,this._el_4,throwOnChange);
    const currVal_13_0_0:any = 'carousel-inner img-thumbnail face back';
    this._NgClass_13_3.check_klass(currVal_13_0_0,throwOnChange,false);
    const currVal_13_0_1:any = this._map_32(this.context.$implicit.isFront);
    this._NgClass_13_3.check_ngClass(currVal_13_0_1,throwOnChange,false);
    this._NgClass_13_3.detectChangesInInputProps(this,this._el_13,throwOnChange);
    const currVal_15_0_0:any = 'item';
    this._NgClass_15_3.check_klass(currVal_15_0_0,throwOnChange,false);
    const currVal_15_0_1:any = this._map_33(!this.context.$implicit.isFront);
    this._NgClass_15_3.check_ngClass(currVal_15_0_1,throwOnChange,false);
    this._NgClass_15_3.detectChangesInInputProps(this,this._el_15,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgClass_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._NgClass_2_3.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this._NgClass_4_3.detectChangesInHostProps(this,this._el_4,throwOnChange);
    const currVal_28:any = this.context.$implicit.path;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_28));
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementProperty(this._el_6,'alt',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementProperty(this._el_6,'title',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_9,currVal_31);
      this._expr_31 = currVal_31;
    }
    this._NgClass_13_3.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._NgClass_15_3.detectChangesInHostProps(this,this._el_15,throwOnChange);
    const currVal_34:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementProperty(this._el_17,'alt',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementProperty(this._el_17,'title',currVal_35);
      this._expr_35 = currVal_35;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this.parent.context.flipCard(this.context.$implicit)) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_GridMemoryComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_GridMemoryComponent1(viewUtils,parentInjector,declarationEl);
}