/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/TourOfHeroes/team.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../app/TourOfHeroes/services/team.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '@angular/common/src/pipes/date_pipe';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/core/src/i18n/tokens';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '@angular/common/src/directives/ng_for';
export class Wrapper_TeamComponent {
  context:import0.TeamComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.TeamComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TeamComponent_Host:import2.RenderComponentType = (null as any);
class _View_TeamComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TeamComponent_0_4:Wrapper_TeamComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TeamComponent_Host0,renderType_TeamComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my-team',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TeamComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TeamComponent_0_4 = new Wrapper_TeamComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.TeamService));
    this._appEl_0.initComponent(this._TeamComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TeamComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TeamComponent) && (0 === requestNodeIndex))) { return this._TeamComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TeamComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TeamComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TeamComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TeamComponent_Host === (null as any))) { (renderType_TeamComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TeamComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TeamComponentNgFactory:import11.ComponentFactory<import0.TeamComponent> = new import11.ComponentFactory<import0.TeamComponent>('my-team',viewFactory_TeamComponent_Host0,import0.TeamComponent);
const styles_TeamComponent:any[] = ([] as any[]);
var renderType_TeamComponent:import2.RenderComponentType = (null as any);
class _View_TeamComponent0 extends import1.AppView<import0.TeamComponent> {
  _el_0:any;
  _RouterLink_0_3:import12.Wrapper_RouterLink;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _TemplateRef_33_5:any;
  _NgFor_33_6:import13.Wrapper_NgFor;
  _text_34:any;
  _text_35:any;
  _arr_40:any;
  _pipe_date_0:import14.DatePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TeamComponent0,renderType_TeamComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_40 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'button',new import4.InlineArray2(2,'class','btn btn-primary pull-right'),(null as any));
    this._RouterLink_0_3 = new import12.Wrapper_RouterLink(this.parentInjector.get(import8.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'span',new import4.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-plus'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,' New player\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,parentRenderNode,'table',new import4.InlineArray2(2,'class','table table-striped'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'thead',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'th',new import4.InlineArray2(2,'style','width: 50px;'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'#',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_9,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'First name',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_9,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Last name',(null as any));
    this._text_19 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_9,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Birthday',(null as any));
    this._text_22 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_9,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Gender',(null as any));
    this._text_25 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_9,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Email',(null as any));
    this._text_28 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_5,'tbody',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._appEl_33 = new import3.AppElement(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import17.TemplateRef_(this._appEl_33,viewFactory_TeamComponent1);
    this._NgFor_33_6 = new import13.Wrapper_NgFor(this._appEl_33.vcRef,this._TemplateRef_33_5,this.parentInjector.get(import18.IterableDiffers),this.ref);
    this._text_34 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_5,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._pipe_date_0 = new import14.DatePipe(this.parentInjector.get(import19.LOCALE_ID));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLink) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLink_0_3.context; }
    if (((token === import17.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import21.NgFor) && (33 === requestNodeIndex))) { return this._NgFor_33_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this._arr_40('/team/player/new');
    this._RouterLink_0_3.check_routerLink(currVal_0_0_0,throwOnChange,false);
    this._RouterLink_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    const currVal_33_0_0:any = this.context.team;
    this._NgFor_33_6.check_ngForOf(currVal_33_0_0,throwOnChange,false);
    this._NgFor_33_6.detectChangesInInputProps(this,this._anchor_33,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLink_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._RouterLink_0_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0_0);
  }
}
export function viewFactory_TeamComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TeamComponent> {
  if ((renderType_TeamComponent === (null as any))) { (renderType_TeamComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_TeamComponent,{})); }
  return new _View_TeamComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TeamComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLink_0_3:import12.Wrapper_RouterLink;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _arr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TeamComponent1,renderType_TeamComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_21 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',new import4.InlineArray2(2,'style','cursor: pointer;'),(null as any));
    this._RouterLink_0_3 = new import12.Wrapper_RouterLink(this.parent.parentInjector.get(import8.Router),this.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parentInjector.get(import16.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._pipe_date_0_0 = import4.pureProxy2((<_View_TeamComponent0>this.parent)._pipe_date_0.transform.bind((<_View_TeamComponent0>this.parent)._pipe_date_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLink) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLink_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_0_0_0:any = this._arr_21('/team/player/edit',this.context.$implicit._id);
    this._RouterLink_0_3.check_routerLink(currVal_0_0_0,throwOnChange,false);
    this._RouterLink_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLink_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    const currVal_22:any = import4.interpolate(1,'',(this.context.index + 1),'');
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_3,currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setText(this._text_6,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = import4.interpolate(1,'',this.context.$implicit.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_9,currVal_24);
      this._expr_24 = currVal_24;
    }
    valUnwrapper.reset();
    const currVal_25:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_TeamComponent0>this.parent)._pipe_date_0.transform)(this.context.$implicit.birthday,'dd-MMM-yyyy')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_25,currVal_25))) {
      this.renderer.setText(this._text_12,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_27:any = import4.interpolate(1,'',this.context.$implicit.gender,'');
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setText(this._text_15,currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = import4.interpolate(1,'',this.context.$implicit.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setText(this._text_18,currVal_28);
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._RouterLink_0_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_TeamComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TeamComponent1(viewUtils,parentInjector,declarationEl);
}