/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/TourOfHeroes/tour-of-heroes.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import11 from '@angular/router/src/router_outlet_map';
import * as import12 from '@angular/core/src/linker/component_factory_resolver';
import * as import13 from '@angular/router/src/directives/router_outlet';
export class Wrapper_TourOfHeroesComponent {
  context:import0.TourOfHeroesComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.TourOfHeroesComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TourOfHeroesComponent_Host:import2.RenderComponentType = (null as any);
class _View_TourOfHeroesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TourOfHeroesComponent_0_4:Wrapper_TourOfHeroesComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TourOfHeroesComponent_Host0,renderType_TourOfHeroesComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'tour-of-heroes',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TourOfHeroesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TourOfHeroesComponent_0_4 = new Wrapper_TourOfHeroesComponent();
    this._appEl_0.initComponent(this._TourOfHeroesComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TourOfHeroesComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TourOfHeroesComponent) && (0 === requestNodeIndex))) { return this._TourOfHeroesComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TourOfHeroesComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TourOfHeroesComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TourOfHeroesComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TourOfHeroesComponent_Host === (null as any))) { (renderType_TourOfHeroesComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TourOfHeroesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TourOfHeroesComponentNgFactory:import9.ComponentFactory<import0.TourOfHeroesComponent> = new import9.ComponentFactory<import0.TourOfHeroesComponent>('tour-of-heroes',viewFactory_TourOfHeroesComponent_Host0,import0.TourOfHeroesComponent);
const styles_TourOfHeroesComponent:any[] = ([] as any[]);
var renderType_TourOfHeroesComponent:import2.RenderComponentType = (null as any);
class _View_TourOfHeroesComponent0 extends import1.AppView<import0.TourOfHeroesComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _RouterOutlet_3_5:import10.Wrapper_RouterOutlet;
  _text_4:any;
  _text_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TourOfHeroesComponent0,renderType_TourOfHeroesComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    this._RouterOutlet_3_5 = new import10.Wrapper_RouterOutlet(this.parentInjector.get(import11.RouterOutletMap),this._appEl_3.vcRef,this.parentInjector.get(import12.ComponentFactoryResolver),(null as any));
    this._text_4 = this.renderer.createText(this._el_1,'\n	',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterOutlet) && (3 === requestNodeIndex))) { return this._RouterOutlet_3_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RouterOutlet_3_5.detectChangesInInputProps(this,this._el_3,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterOutlet_3_5.detectChangesInHostProps(this,this._el_3,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_3_5.context.ngOnDestroy();
  }
}
export function viewFactory_TourOfHeroesComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TourOfHeroesComponent> {
  if ((renderType_TourOfHeroesComponent === (null as any))) { (renderType_TourOfHeroesComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_TourOfHeroesComponent,{})); }
  return new _View_TourOfHeroesComponent0(viewUtils,parentInjector,declarationEl);
}