/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/subapps/grid-memory/grid-memory.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../app/subapps/grid-memory/grid-memory.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from './grid-memory.component.css.shim';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import13 from '../../../../app/spinner/my-spinner.component';
import * as import14 from '../../spinner/my-spinner.component.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import19 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/common/src/directives/ng_class';
import * as import22 from '@angular/core/src/security';
export class Wrapper_GridMemoryComponent {
  /*private*/ _eventHandler:Function;
  context:import0.GridMemoryComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.GridMemoryComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_GridMemoryComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_GridMemoryComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.GridMemoryComponent>;
  _GridMemoryService_0_3:import5.GridMemoryService;
  _GridMemoryComponent_0_4:Wrapper_GridMemoryComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GridMemoryComponent_Host0,renderType_GridMemoryComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-grid-memory',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_GridMemoryComponent0(this.viewUtils,this,0,this._el_0);
    this._GridMemoryService_0_3 = new import5.GridMemoryService(this.injectorGet(import9.Http,this.parentIndex));
    this._GridMemoryComponent_0_4 = new Wrapper_GridMemoryComponent(this._GridMemoryService_0_3);
    this.compView_0.create(this._GridMemoryComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._GridMemoryComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.GridMemoryService) && (0 === requestNodeIndex))) { return this._GridMemoryService_0_3; }
    if (((token === import0.GridMemoryComponent) && (0 === requestNodeIndex))) { return this._GridMemoryComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._GridMemoryComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const GridMemoryComponentNgFactory:import8.ComponentFactory<import0.GridMemoryComponent> = new import8.ComponentFactory<import0.GridMemoryComponent>('my-grid-memory',View_GridMemoryComponent_Host0,import0.GridMemoryComponent);
const styles_GridMemoryComponent:any[] = [import10.styles];
var renderType_GridMemoryComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_GridMemoryComponent,{});
export class View_GridMemoryComponent0 extends import1.AppView<import0.GridMemoryComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import11.ViewContainer;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import12.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  compView_47:import1.AppView<import13.MySpinner>;
  _MySpinner_47_3:import14.Wrapper_MySpinner;
  _text_48:any;
  _el_49:any;
  compView_49:import1.AppView<import13.MySpinner>;
  _MySpinner_49_3:import14.Wrapper_MySpinner;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_GridMemoryComponent0,renderType_GridMemoryComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray2(2,'style','width: 100%;'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'td',new import3.InlineArray2(2,'colspan','2'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'button',new import3.InlineArray2(2,'class','btn btn-sm btn-default'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'span',new import3.InlineArray2(2,'class','glyphicon glyphicon-refresh'),(null as any));
    this._text_15 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','text-primary'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_4,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._vc_27 = new import11.ViewContainer(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import15.TemplateRef_(this,27,this._anchor_27);
    this._NgFor_27_6 = new import12.Wrapper_NgFor(this._vc_27.vcRef,this._TemplateRef_27_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_23,'td',new import3.InlineArray8(6,'class','media-right ','rowspan','2','style','width: 75px;'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray4(4,'class','btn-group-vertical center-block','role','group'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n                    ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'button',new import3.InlineArray2(2,'class','btn btn-sm btn-success disabled'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'span',new import3.InlineArray2(2,'class','label label-success badge'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n                    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_32,'\n                    ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_32,'button',new import3.InlineArray2(2,'class','btn btn-sm btn-danger disabled'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'span',new import3.InlineArray2(2,'class','label label-danger badge'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_32,'\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray4(4,'bdgClass','glyphicon-th','mySpinner',''),(null as any));
    this.compView_47 = new import14.View_MySpinner0(this.viewUtils,this,47,this._el_47);
    this._MySpinner_47_3 = new import14.Wrapper_MySpinner();
    this.compView_47.create(this._MySpinner_47_3.context);
    this._text_48 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray4(4,'bdgClass','glyphicon-time','mySpinner',''),(null as any));
    this.compView_49 = new import14.View_MySpinner0(this.viewUtils,this,49,this._el_49);
    this._MySpinner_49_3 = new import14.Wrapper_MySpinner();
    this.compView_49.create(this._MySpinner_49_3.context);
    this._text_50 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._text_51 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'counterChange',(null as any)),this.eventHandler(this.handleEvent_47));
    this._MySpinner_47_3.subscribe(this,this.eventHandler(this.handleEvent_47),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_49,new import3.InlineArray2(2,'counterChange',(null as any)),this.eventHandler(this.handleEvent_49));
    this._MySpinner_49_3.subscribe(this,this.eventHandler(this.handleEvent_49),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import17.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import13.MySpinner) && (47 === requestNodeIndex))) { return this._MySpinner_47_3.context; }
    if (((token === import13.MySpinner) && (49 === requestNodeIndex))) { return this._MySpinner_49_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_27_0_0:any = this.context.files;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    const currVal_47_0_0:any = this.context.limit;
    this._MySpinner_47_3.check_counterValue(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = 'glyphicon-th';
    this._MySpinner_47_3.check_bdgClass(currVal_47_0_1,throwOnChange,false);
    this._MySpinner_47_3.ngDoCheck(this,this._el_47,throwOnChange);
    const currVal_49_0_0:any = this.context.seconds;
    this._MySpinner_49_3.check_counterValue(currVal_49_0_0,throwOnChange,false);
    const currVal_49_0_1:any = 'glyphicon-time';
    this._MySpinner_49_3.check_bdgClass(currVal_49_0_1,throwOnChange,false);
    this._MySpinner_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    const currVal_63:any = import3.inlineInterpolate(1,'',this.context.question,'');
    if (import3.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setText(this._text_18,currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = import3.inlineInterpolate(1,'',this.context.countSuc,'');
    if (import3.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setText(this._text_37,currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = import3.inlineInterpolate(1,'',this.context.countErr,'');
    if (import3.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setText(this._text_43,currVal_65);
      this._expr_65 = currVal_65;
    }
    this.compView_47.detectChanges(throwOnChange);
    this.compView_49.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_27.destroyNestedViews();
    this.compView_47.destroy();
    this.compView_49.destroy();
    this._MySpinner_47_3.ngOnDestroy();
    this._MySpinner_49_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 27)) { return new View_GridMemoryComponent1(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    return (null as any);
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickReload()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'counterChange')) {
      const pd_sub_0:any = ((<any>this.context.onChangeLimit($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_49(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'counterChange')) {
      const pd_sub_0:any = ((<any>this.context.onChangeTimeout($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_GridMemoryComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgClass_0_3:import18.Wrapper_NgClass;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import18.Wrapper_NgClass;
  _text_3:any;
  _el_4:any;
  _NgClass_4_3:import18.Wrapper_NgClass;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _NgClass_13_3:import18.Wrapper_NgClass;
  _text_14:any;
  _el_15:any;
  _NgClass_15_3:import18.Wrapper_NgClass;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _map_26:any;
  _map_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  _map_32:any;
  _map_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_GridMemoryComponent1,renderType_GridMemoryComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_26 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {hidden: p0};
    });
    this._map_27 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._map_32 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {hidden: p0};
    });
    this._map_33 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','carousel slide card','data-ride','carousel'),(null as any));
    this._NgClass_0_3 = new import18.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray4(4,'class','carousel-inner  img-thumbnail face front','role','listbox'),(null as any));
    this._NgClass_2_3 = new import18.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','item'),(null as any));
    this._NgClass_4_3 = new import18.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_4,'\n                            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'img',new import3.InlineArray2(2,'class','img-responsive'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n                            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','carousel-caption'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','carousel-inner img-thumbnail face back'),(null as any));
    this._NgClass_13_3 = new import18.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','item'),(null as any));
    this._NgClass_15_3 = new import18.Wrapper_NgClass(this.parentView.parentView.injectorGet(import16.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import19.KeyValueDiffers,this.parentView.parentIndex),new import20.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText(this._el_15,'\n                            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'img',new import3.InlineArray4(4,'class','img-responsive','src','/components/cover.jpg'),(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'click',(null as any),'touch',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.NgClass) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._NgClass_4_3.context; }
    if (((token === import21.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgClass_2_3.context; }
    if (((token === import21.NgClass) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgClass_15_3.context; }
    if (((token === import21.NgClass) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_13_3.context; }
    if (((token === import21.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'carousel slide card';
    this._NgClass_0_3.check_klass(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.cardClasses;
    this._NgClass_0_3.check_ngClass(currVal_0_0_1,throwOnChange,false);
    this._NgClass_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = 'carousel-inner  img-thumbnail face front';
    this._NgClass_2_3.check_klass(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = this._map_26(!this.context.$implicit.isFront);
    this._NgClass_2_3.check_ngClass(currVal_2_0_1,throwOnChange,false);
    this._NgClass_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = 'item';
    this._NgClass_4_3.check_klass(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = this._map_27(this.context.$implicit.isFront);
    this._NgClass_4_3.check_ngClass(currVal_4_0_1,throwOnChange,false);
    this._NgClass_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_13_0_0:any = 'carousel-inner img-thumbnail face back';
    this._NgClass_13_3.check_klass(currVal_13_0_0,throwOnChange,false);
    const currVal_13_0_1:any = this._map_32(this.context.$implicit.isFront);
    this._NgClass_13_3.check_ngClass(currVal_13_0_1,throwOnChange,false);
    this._NgClass_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_15_0_0:any = 'item';
    this._NgClass_15_3.check_klass(currVal_15_0_0,throwOnChange,false);
    const currVal_15_0_1:any = this._map_33(!this.context.$implicit.isFront);
    this._NgClass_15_3.check_ngClass(currVal_15_0_1,throwOnChange,false);
    this._NgClass_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_28:any = this.context.$implicit.path;
    if (import3.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_28));
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementProperty(this._el_6,'alt',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementProperty(this._el_6,'title',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_9,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_34:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementProperty(this._el_17,'alt',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementProperty(this._el_17,'title',currVal_35);
      this._expr_35 = currVal_35;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.flipCard(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'touch')) {
      const pd_sub_1:any = ((<any>this.parentView.context.flipCard(this.context.$implicit)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}