/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../app/TourOfHeroes/providers/team-firebase-provider.service';
import * as import5 from '../../app/TourOfHeroes/services/team.service';
import * as import6 from '../../app/nav/sb-router.service';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../app/TourOfHeroes/providers/team-provider.service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from './nav/nav.component.ngfactory';
import * as import16 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import17 from '@angular/router/src/router_outlet_map';
import * as import18 from '@angular/core/src/linker/component_factory_resolver';
import * as import19 from '../../app/nav/nav.component';
import * as import20 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  __TeamProvider_0_5:import4.TeamFirebaseProvider;
  __TeamService_0_6:import5.TeamService;
  __SbRouterService_0_7:import6.SbRouterService;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  get _TeamProvider_0_5():import4.TeamFirebaseProvider {
    if ((this.__TeamProvider_0_5 == (null as any))) { (this.__TeamProvider_0_5 = new import4.TeamFirebaseProvider()); }
    return this.__TeamProvider_0_5;
  }
  get _TeamService_0_6():import5.TeamService {
    if ((this.__TeamService_0_6 == (null as any))) { (this.__TeamService_0_6 = new import5.TeamService(this._TeamProvider_0_5)); }
    return this.__TeamService_0_6;
  }
  get _SbRouterService_0_7():import6.SbRouterService {
    if ((this.__SbRouterService_0_7 == (null as any))) { (this.__SbRouterService_0_7 = new import6.SbRouterService(this.parentInjector.get(import11.Router))); }
    return this.__SbRouterService_0_7;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import7.selectOrCreateRenderHostElement(this.renderer,'my-app',import7.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    if (((token === import12.TeamProvider) && (0 === requestNodeIndex))) { return this._TeamProvider_0_5; }
    if (((token === import5.TeamService) && (0 === requestNodeIndex))) { return this._TeamService_0_6; }
    if (((token === import6.SbRouterService) && (0 === requestNodeIndex))) { return this._SbRouterService_0_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import14.ComponentFactory<import0.AppComponent> = new import14.ComponentFactory<import0.AppComponent>('my-app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _NavComponent_1_4:import15.Wrapper_NavComponent;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _RouterOutlet_5_5:import16.Wrapper_RouterOutlet;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_1 = import7.createRenderElement(this.renderer,parentRenderNode,'my-nav',import7.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import15.viewFactory_NavComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._NavComponent_1_4 = new import15.Wrapper_NavComponent();
    this._appEl_1.initComponent(this._NavComponent_1_4.context,([] as any[]),compView_1);
    compView_1.create(this._NavComponent_1_4.context,([] as any[]),(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this._el_3 = import7.createRenderElement(this.renderer,parentRenderNode,'div',new import7.InlineArray2(2,'class','container'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = import7.createRenderElement(this.renderer,this._el_3,'router-outlet',import7.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    this._RouterOutlet_5_5 = new import16.Wrapper_RouterOutlet(this.parentInjector.get(import17.RouterOutletMap),this._appEl_5.vcRef,this.parentInjector.get(import18.ComponentFactoryResolver),(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NavComponent) && (1 === requestNodeIndex))) { return this._NavComponent_1_4.context; }
    if (((token === import20.RouterOutlet) && (5 === requestNodeIndex))) { return this._RouterOutlet_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavComponent_1_4.detectChangesInInputProps(this,this._el_1,throwOnChange);
    this._RouterOutlet_5_5.detectChangesInInputProps(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NavComponent_1_4.detectChangesInHostProps(this,this._el_1,throwOnChange);
    this._RouterOutlet_5_5.detectChangesInHostProps(this,this._el_5,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_5_5.context.ngOnDestroy();
  }
}
export function viewFactory_AppComponent0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}