/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../app/subapps/tour-of-heroes/providers/team-firebase-provider.service';
import * as import6 from '../../app/subapps/tour-of-heroes/services/team.service';
import * as import7 from '../../app/nav/sb-router.service';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/constants';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../app/subapps/tour-of-heroes/providers/team-provider.service';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../../app/nav/nav.component';
import * as import15 from './nav/nav.component.ngfactory';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  __TeamProvider_0_4:import5.TeamFirebaseProvider;
  __TeamService_0_5:import6.TeamService;
  __SbRouterService_0_6:import7.SbRouterService;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  get _TeamProvider_0_4():import5.TeamFirebaseProvider {
    if ((this.__TeamProvider_0_4 == null)) { (this.__TeamProvider_0_4 = new import5.TeamFirebaseProvider()); }
    return this.__TeamProvider_0_4;
  }
  get _TeamService_0_5():import6.TeamService {
    if ((this.__TeamService_0_5 == null)) { (this.__TeamService_0_5 = new import6.TeamService(this._TeamProvider_0_4)); }
    return this.__TeamService_0_5;
  }
  get _SbRouterService_0_6():import7.SbRouterService {
    if ((this.__SbRouterService_0_6 == null)) { (this.__SbRouterService_0_6 = new import7.SbRouterService(this.injectorGet(import10.Router,this.parentIndex))); }
    return this.__SbRouterService_0_6;
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import11.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    if (((token === import12.TeamProvider) && (0 === requestNodeIndex))) { return this._TeamProvider_0_4; }
    if (((token === import6.TeamService) && (0 === requestNodeIndex))) { return this._TeamService_0_5; }
    if (((token === import7.SbRouterService) && (0 === requestNodeIndex))) { return this._SbRouterService_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import11.ComponentFactory<import0.AppComponent> = new import11.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _viewQuery_mainContainer_0:import13.QueryList<any>;
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import14.NavComponent>;
  _NavComponent_1_3:import15.Wrapper_NavComponent;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _vc_5:import16.ViewContainer;
  _RouterOutlet_5_5:import17.Wrapper_RouterOutlet;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import11.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_mainContainer_0 = new import13.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'my-nav',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import15.View_NavComponent0(this.viewUtils,this,1,this._el_1);
    this._NavComponent_1_3 = new import15.Wrapper_NavComponent();
    this.compView_1.create(this._NavComponent_1_3.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container','id','mainContainer'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_5 = new import16.ViewContainer(5,3,this,this._el_5);
    this._RouterOutlet_5_5 = new import17.Wrapper_RouterOutlet(this.parentView.injectorGet(import18.RouterOutletMap,this.parentIndex),this._vc_5.vcRef,this.parentView.injectorGet(import19.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._viewQuery_mainContainer_0.reset([new import20.ElementRef(this._el_3)]);
    this.context.mainContainer = this._viewQuery_mainContainer_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NavComponent) && (1 === requestNodeIndex))) { return this._NavComponent_1_3.context; }
    if (((token === import21.RouterOutlet) && (5 === requestNodeIndex))) { return this._RouterOutlet_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavComponent_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    this._RouterOutlet_5_5.ngDoCheck(this,this._el_5,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this.compView_1.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this.compView_1.destroy();
    this._RouterOutlet_5_5.ngOnDestroy();
  }
}