[
{path:"/1.jpg",langs:[
{name:"en",value:"1"},
{name:"ru",value:"1"}
]},
{path:"/10.jpg",langs:[
{name:"en",value:"10"},
{name:"ru",value:"10"}
]},
{path:"/100.jpg",langs:[
{name:"en",value:"100"},
{name:"ru",value:"100"}
]},
{path:"/11.jpg",langs:[
{name:"en",value:"11"},
{name:"ru",value:"11"}
]},
{path:"/12.jpg",langs:[
{name:"en",value:"12"},
{name:"ru",value:"12"}
]},
{path:"/13.jpg",langs:[
{name:"en",value:"13"},
{name:"ru",value:"13"}
]},
{path:"/14.jpg",langs:[
{name:"en",value:"14"},
{name:"ru",value:"14"}
]},
{path:"/15.jpg",langs:[
{name:"en",value:"15"},
{name:"ru",value:"15"}
]},
{path:"/16.jpg",langs:[
{name:"en",value:"16"},
{name:"ru",value:"16"}
]},
{path:"/17.jpg",langs:[
{name:"en",value:"17"},
{name:"ru",value:"17"}
]},
{path:"/18.jpg",langs:[
{name:"en",value:"18"},
{name:"ru",value:"18"}
]},
{path:"/19.jpg",langs:[
{name:"en",value:"19"},
{name:"ru",value:"19"}
]},
{path:"/2.jpg",langs:[
{name:"en",value:"2"},
{name:"ru",value:"2"}
]},
{path:"/20.jpg",langs:[
{name:"en",value:"20"},
{name:"ru",value:"20"}
]},
{path:"/21.jpg",langs:[
{name:"en",value:"21"},
{name:"ru",value:"21"}
]},
{path:"/22.jpg",langs:[
{name:"en",value:"22"},
{name:"ru",value:"22"}
]},
{path:"/23.jpg",langs:[
{name:"en",value:"23"},
{name:"ru",value:"23"}
]},
{path:"/24.jpg",langs:[
{name:"en",value:"24"},
{name:"ru",value:"24"}
]},
{path:"/25.jpg",langs:[
{name:"en",value:"25"},
{name:"ru",value:"25"}
]},
{path:"/26.jpg",langs:[
{name:"en",value:"26"},
{name:"ru",value:"26"}
]},
{path:"/27.jpg",langs:[
{name:"en",value:"27"},
{name:"ru",value:"27"}
]},
{path:"/28.jpg",langs:[
{name:"en",value:"28"},
{name:"ru",value:"28"}
]},
{path:"/29.jpg",langs:[
{name:"en",value:"29"},
{name:"ru",value:"29"}
]},
{path:"/3.jpg",langs:[
{name:"en",value:"3"},
{name:"ru",value:"3"}
]},
{path:"/30.jpg",langs:[
{name:"en",value:"30"},
{name:"ru",value:"30"}
]},
{path:"/31.jpg",langs:[
{name:"en",value:"31"},
{name:"ru",value:"31"}
]},
{path:"/32.jpg",langs:[
{name:"en",value:"32"},
{name:"ru",value:"32"}
]},
{path:"/33.jpg",langs:[
{name:"en",value:"33"},
{name:"ru",value:"33"}
]},
{path:"/34.jpg",langs:[
{name:"en",value:"34"},
{name:"ru",value:"34"}
]},
{path:"/35.jpg",langs:[
{name:"en",value:"35"},
{name:"ru",value:"35"}
]},
{path:"/36.jpg",langs:[
{name:"en",value:"36"},
{name:"ru",value:"36"}
]},
{path:"/37.jpg",langs:[
{name:"en",value:"37"},
{name:"ru",value:"37"}
]},
{path:"/38.jpg",langs:[
{name:"en",value:"38"},
{name:"ru",value:"38"}
]},
{path:"/39.jpg",langs:[
{name:"en",value:"39"},
{name:"ru",value:"39"}
]},
{path:"/4.jpg",langs:[
{name:"en",value:"4"},
{name:"ru",value:"4"}
]},
{path:"/40.jpg",langs:[
{name:"en",value:"40"},
{name:"ru",value:"40"}
]},
{path:"/41.jpg",langs:[
{name:"en",value:"41"},
{name:"ru",value:"41"}
]},
{path:"/42.jpg",langs:[
{name:"en",value:"42"},
{name:"ru",value:"42"}
]},
{path:"/43.jpg",langs:[
{name:"en",value:"43"},
{name:"ru",value:"43"}
]},
{path:"/44.jpg",langs:[
{name:"en",value:"44"},
{name:"ru",value:"44"}
]},
{path:"/45.jpg",langs:[
{name:"en",value:"45"},
{name:"ru",value:"45"}
]},
{path:"/46.jpg",langs:[
{name:"en",value:"46"},
{name:"ru",value:"46"}
]},
{path:"/47.jpg",langs:[
{name:"en",value:"47"},
{name:"ru",value:"47"}
]},
{path:"/48.jpg",langs:[
{name:"en",value:"48"},
{name:"ru",value:"48"}
]},
{path:"/49.jpg",langs:[
{name:"en",value:"49"},
{name:"ru",value:"49"}
]},
{path:"/5.jpg",langs:[
{name:"en",value:"5"},
{name:"ru",value:"5"}
]},
{path:"/50.jpg",langs:[
{name:"en",value:"50"},
{name:"ru",value:"50"}
]},
{path:"/51.jpg",langs:[
{name:"en",value:"51"},
{name:"ru",value:"51"}
]},
{path:"/52.jpg",langs:[
{name:"en",value:"52"},
{name:"ru",value:"52"}
]},
{path:"/53.jpg",langs:[
{name:"en",value:"53"},
{name:"ru",value:"53"}
]},
{path:"/54.jpg",langs:[
{name:"en",value:"54"},
{name:"ru",value:"54"}
]},
{path:"/55.jpg",langs:[
{name:"en",value:"55"},
{name:"ru",value:"55"}
]},
{path:"/56.jpg",langs:[
{name:"en",value:"56"},
{name:"ru",value:"56"}
]},
{path:"/57.jpg",langs:[
{name:"en",value:"57"},
{name:"ru",value:"57"}
]},
{path:"/58.jpg",langs:[
{name:"en",value:"58"},
{name:"ru",value:"58"}
]},
{path:"/59.jpg",langs:[
{name:"en",value:"59"},
{name:"ru",value:"59"}
]},
{path:"/6.jpg",langs:[
{name:"en",value:"6"},
{name:"ru",value:"6"}
]},
{path:"/60.jpg",langs:[
{name:"en",value:"60"},
{name:"ru",value:"60"}
]},
{path:"/62.jpg",langs:[
{name:"en",value:"62"},
{name:"ru",value:"62"}
]},
{path:"/63.jpg",langs:[
{name:"en",value:"63"},
{name:"ru",value:"63"}
]},
{path:"/64.jpg",langs:[
{name:"en",value:"64"},
{name:"ru",value:"64"}
]},
{path:"/65.jpg",langs:[
{name:"en",value:"65"},
{name:"ru",value:"65"}
]},
{path:"/66.jpg",langs:[
{name:"en",value:"66"},
{name:"ru",value:"66"}
]},
{path:"/67.jpg",langs:[
{name:"en",value:"67"},
{name:"ru",value:"67"}
]},
{path:"/68.jpg",langs:[
{name:"en",value:"68"},
{name:"ru",value:"68"}
]},
{path:"/69.jpg",langs:[
{name:"en",value:"69"},
{name:"ru",value:"69"}
]},
{path:"/7.jpg",langs:[
{name:"en",value:"7"},
{name:"ru",value:"7"}
]},
{path:"/70.jpg",langs:[
{name:"en",value:"70"},
{name:"ru",value:"70"}
]},
{path:"/71.jpg",langs:[
{name:"en",value:"71"},
{name:"ru",value:"71"}
]},
{path:"/72.jpg",langs:[
{name:"en",value:"72"},
{name:"ru",value:"72"}
]},
{path:"/73.jpg",langs:[
{name:"en",value:"73"},
{name:"ru",value:"73"}
]},
{path:"/74.jpg",langs:[
{name:"en",value:"74"},
{name:"ru",value:"74"}
]},
{path:"/75.jpg",langs:[
{name:"en",value:"75"},
{name:"ru",value:"75"}
]},
{path:"/76.jpg",langs:[
{name:"en",value:"76"},
{name:"ru",value:"76"}
]},
{path:"/77.jpg",langs:[
{name:"en",value:"77"},
{name:"ru",value:"77"}
]},
{path:"/78.jpg",langs:[
{name:"en",value:"78"},
{name:"ru",value:"78"}
]},
{path:"/79.jpg",langs:[
{name:"en",value:"79"},
{name:"ru",value:"79"}
]},
{path:"/8.jpg",langs:[
{name:"en",value:"8"},
{name:"ru",value:"8"}
]},
{path:"/80.jpg",langs:[
{name:"en",value:"80"},
{name:"ru",value:"80"}
]},
{path:"/81.jpg",langs:[
{name:"en",value:"81"},
{name:"ru",value:"81"}
]},
{path:"/82.jpg",langs:[
{name:"en",value:"82"},
{name:"ru",value:"82"}
]},
{path:"/83.jpg",langs:[
{name:"en",value:"83"},
{name:"ru",value:"83"}
]},
{path:"/84.jpg",langs:[
{name:"en",value:"84"},
{name:"ru",value:"84"}
]},
{path:"/85.jpg",langs:[
{name:"en",value:"85"},
{name:"ru",value:"85"}
]},
{path:"/86.jpg",langs:[
{name:"en",value:"86"},
{name:"ru",value:"86"}
]},
{path:"/87.jpg",langs:[
{name:"en",value:"87"},
{name:"ru",value:"87"}
]},
{path:"/88.jpg",langs:[
{name:"en",value:"88"},
{name:"ru",value:"88"}
]},
{path:"/89.jpg",langs:[
{name:"en",value:"89"},
{name:"ru",value:"89"}
]},
{path:"/9.jpg",langs:[
{name:"en",value:"9"},
{name:"ru",value:"9"}
]},
{path:"/90.jpg",langs:[
{name:"en",value:"90"},
{name:"ru",value:"90"}
]},
{path:"/91.jpg",langs:[
{name:"en",value:"91"},
{name:"ru",value:"91"}
]},
{path:"/92.jpg",langs:[
{name:"en",value:"92"},
{name:"ru",value:"92"}
]},
{path:"/93.jpg",langs:[
{name:"en",value:"93"},
{name:"ru",value:"93"}
]},
{path:"/94.jpg",langs:[
{name:"en",value:"94"},
{name:"ru",value:"94"}
]},
{path:"/95.jpg",langs:[
{name:"en",value:"95"},
{name:"ru",value:"95"}
]},
{path:"/96.jpg",langs:[
{name:"en",value:"96"},
{name:"ru",value:"96"}
]},
{path:"/97.jpg",langs:[
{name:"en",value:"97"},
{name:"ru",value:"97"}
]},
{path:"/98.jpg",langs:[
{name:"en",value:"98"},
{name:"ru",value:"98"}
]},
{path:"/99.jpg",langs:[
{name:"en",value:"99"},
{name:"ru",value:"99"}
]},
]