/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.votingWdt[_ngcontent-%COMP%] {\r\n}\r\n\r\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:first-child, .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:last-child {\r\n        padding-bottom: 3px !important;\r\n        padding-top: 3px !important;\r\n    }\r\n\r\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:first-child {\r\n        padding-bottom: 0 !important;\r\n        border-bottom-width: 0;\r\n    }\r\n\r\n    .votingWdt[_ngcontent-%COMP%]    > .btn.disabled[_ngcontent-%COMP%] {\r\n        padding-top: 3px !important;\r\n        padding-bottom: 3px !important;\r\n        border-top-width: 0;\r\n        border-bottom-width: 0;\r\n    }\r\n\r\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:last-child {\r\n        padding-top: 0 !important;\r\n        border-top-width: 0;\r\n    }'];