/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
/* tslint:disable */
export var styles = ['.votingWdt[_ngcontent-%COMP%] {\n}\n\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:first-child, .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:last-child {\n        padding-left: 3px !important;\n        padding-right: 3px !important;\n    }\n\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:first-child {\n        padding-right: 0 !important;\n        border-right-width: 0;\n    }\n\n    .votingWdt[_ngcontent-%COMP%]    > .btn.disabled[_ngcontent-%COMP%] {\n        padding-left: 3px !important;\n        padding-right: 3px !important;\n        border-left-width: 0;\n        border-right-width: 0;\n    }\n\n    .votingWdt[_ngcontent-%COMP%]    > .btn[_ngcontent-%COMP%]:last-child {\n        padding-left: 0 !important;\n        border-left-width: 0;\n    }'];
//# sourceMappingURL=my-spinner.component.css.shim.js.map