/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/nav/nav.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/common/src/location/location_strategy';
import * as import12 from '@angular/router/src/directives/router_link';
export class Wrapper_NavComponent {
  /*private*/ _eventHandler:Function;
  context:import0.NavComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.NavComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_NavComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_NavComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.NavComponent>;
  _NavComponent_0_3:Wrapper_NavComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavComponent_Host0,renderType_NavComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-nav',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_NavComponent0(this.viewUtils,this,0,this._el_0);
    this._NavComponent_0_3 = new Wrapper_NavComponent();
    this.compView_0.create(this._NavComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._NavComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NavComponent) && (0 === requestNodeIndex))) { return this._NavComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NavComponentNgFactory:import7.ComponentFactory<import0.NavComponent> = new import7.ComponentFactory<import0.NavComponent>('my-nav',View_NavComponent_Host0,import0.NavComponent);
const styles_NavComponent:any[] = ([] as any[]);
var renderType_NavComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_NavComponent,{});
export class View_NavComponent0 extends import1.AppView<import0.NavComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import8.Wrapper_RouterLinkWithHref;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _el_42:any;
  _RouterLinkWithHref_42_3:import8.Wrapper_RouterLinkWithHref;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _el_46:any;
  _RouterLinkWithHref_46_3:import8.Wrapper_RouterLinkWithHref;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _el_50:any;
  _RouterLinkWithHref_50_3:import8.Wrapper_RouterLinkWithHref;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _arr_65:any;
  _arr_66:any;
  _arr_67:any;
  _arr_68:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavComponent0,renderType_NavComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_65 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_66 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_67 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_68 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-inverse navbar-fixed-top'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'button',new import3.InlineArray16(10,'aria-expanded','false','class','navbar-toggle collapsed','data-target','#sb-top-navigation','data-toggle','collapse','type','button'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_7,'span',new import3.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'a',new import3.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Brand',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','sb-top-navigation'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'ul',new import3.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_28 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_26,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_29,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_30_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_31 = this.renderer.createText(this._el_30,'Home',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_26,'li',new import3.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'a',new import3.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle','data-toggle','dropdown','href','#','role','button'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Apps',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'span',new import3.InlineArray2(2,'class','caret'),(null as any));
    this._text_38 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_33,'ul',new import3.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_41,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_42_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_43 = this.renderer.createText(this._el_42,'Memory grid',(null as any));
    this._text_44 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_39,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_45,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_46_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_47 = this.renderer.createText(this._el_46,'Tour of heroes (Angular.io)',(null as any));
    this._text_48 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_39,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_49,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_50_3 = new import8.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import10.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import11.LocationStrategy,this.parentIndex));
    this._text_51 = this.renderer.createText(this._el_50,'2048',(null as any));
    this._text_52 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_54 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_55 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_59 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_60 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_30));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_42));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_46,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_46));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_50));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkWithHref_30_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._RouterLinkWithHref_42_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._RouterLinkWithHref_46_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._RouterLinkWithHref_50_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_30_0_0:any = this._arr_65('');
    this._RouterLinkWithHref_30_3.check_routerLink(currVal_30_0_0,throwOnChange,false);
    this._RouterLinkWithHref_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_42_0_0:any = this._arr_66('/memory-grid');
    this._RouterLinkWithHref_42_3.check_routerLink(currVal_42_0_0,throwOnChange,false);
    this._RouterLinkWithHref_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_46_0_0:any = this._arr_67('/team');
    this._RouterLinkWithHref_46_3.check_routerLink(currVal_46_0_0,throwOnChange,false);
    this._RouterLinkWithHref_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_50_0_0:any = this._arr_68('/2048');
    this._RouterLinkWithHref_50_3.check_routerLink(currVal_50_0_0,throwOnChange,false);
    this._RouterLinkWithHref_50_3.ngDoCheck(this,this._el_50,throwOnChange);
    this._RouterLinkWithHref_30_3.checkHost(this,this,this._el_30,throwOnChange);
    this._RouterLinkWithHref_42_3.checkHost(this,this,this._el_42,throwOnChange);
    this._RouterLinkWithHref_46_3.checkHost(this,this,this._el_46,throwOnChange);
    this._RouterLinkWithHref_50_3.checkHost(this,this,this._el_50,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_30_3.ngOnDestroy();
    this._RouterLinkWithHref_42_3.ngOnDestroy();
    this._RouterLinkWithHref_46_3.ngOnDestroy();
    this._RouterLinkWithHref_50_3.ngOnDestroy();
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_30_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_42_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_46(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_46_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_50_3.handleEvent(eventName,$event) && result);
    return result;
  }
}