/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/nav/nav.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/router/src/router_state';
import * as import13 from '@angular/common/src/location/location_strategy';
import * as import14 from '@angular/router/src/directives/router_link';
export class Wrapper_NavComponent {
  context:import0.NavComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.NavComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_NavComponent_Host:import2.RenderComponentType = (null as any);
class _View_NavComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _NavComponent_0_4:Wrapper_NavComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NavComponent_Host0,renderType_NavComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my-nav',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NavComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NavComponent_0_4 = new Wrapper_NavComponent();
    this._appEl_0.initComponent(this._NavComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NavComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NavComponent) && (0 === requestNodeIndex))) { return this._NavComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NavComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NavComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NavComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_NavComponent_Host === (null as any))) { (renderType_NavComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NavComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavComponentNgFactory:import9.ComponentFactory<import0.NavComponent> = new import9.ComponentFactory<import0.NavComponent>('my-nav',viewFactory_NavComponent_Host0,import0.NavComponent);
const styles_NavComponent:any[] = ([] as any[]);
var renderType_NavComponent:import2.RenderComponentType = (null as any);
class _View_NavComponent0 extends import1.AppView<import0.NavComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import10.Wrapper_RouterLinkWithHref;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _el_42:any;
  _RouterLinkWithHref_42_3:import10.Wrapper_RouterLinkWithHref;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _el_46:any;
  _RouterLinkWithHref_46_3:import10.Wrapper_RouterLinkWithHref;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _arr_60:any;
  _arr_61:any;
  _arr_62:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NavComponent0,renderType_NavComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_60 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_61 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_62 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'nav',new import4.InlineArray2(2,'class','navbar navbar-inverse navbar-fixed-top'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'button',new import4.InlineArray16(10,'aria-expanded','false','class','navbar-toggle collapsed','data-target','#bs-example-navbar-collapse-1','data-toggle','collapse','type','button'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'span',new import4.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_7,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_7,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_7,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_5,'a',new import4.InlineArray4(4,'class','navbar-brand','href','#'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Brand',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray4(4,'class','collapse navbar-collapse','id','bs-example-navbar-collapse-1'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_24,'ul',new import4.InlineArray2(2,'class','nav navbar-nav'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._text_28 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_29 = import4.createRenderElement(this.renderer,this._el_26,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_29,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_30_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import11.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_31 = this.renderer.createText(this._el_30,'Home',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_26,'li',new import4.InlineArray2(2,'class','dropdown'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n					',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_33,'a',new import4.InlineArray16(12,'aria-expanded','false','aria-haspopup','true','class','dropdown-toggle','data-toggle','dropdown','href','#','role','button'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Apps',(null as any));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_35,'span',new import4.InlineArray2(2,'class','caret'),(null as any));
    this._text_38 = this.renderer.createText(this._el_33,'\n					',(null as any));
    this._el_39 = import4.createRenderElement(this.renderer,this._el_33,'ul',new import4.InlineArray2(2,'class','dropdown-menu'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n						',(null as any));
    this._el_41 = import4.createRenderElement(this.renderer,this._el_39,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_42 = import4.createRenderElement(this.renderer,this._el_41,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_42_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import11.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_43 = this.renderer.createText(this._el_42,'Memory grid',(null as any));
    this._text_44 = this.renderer.createText(this._el_39,'\n						',(null as any));
    this._el_45 = import4.createRenderElement(this.renderer,this._el_39,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_46 = import4.createRenderElement(this.renderer,this._el_45,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_46_3 = new import10.Wrapper_RouterLinkWithHref(this.parentInjector.get(import11.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_47 = this.renderer.createText(this._el_46,'Team',(null as any));
    this._text_48 = this.renderer.createText(this._el_39,'\n					',(null as any));
    this._text_49 = this.renderer.createText(this._el_33,'\n				',(null as any));
    this._text_50 = this.renderer.createText(this._el_26,'\n			',(null as any));
    this._text_51 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._text_52 = this.renderer.createText(this._el_24,'\n		',(null as any));
    this._text_53 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_54 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_55 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._text_56 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_46,'click',this.eventHandler(this._handle_click_46_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RouterLinkWithHref_30_3.context; }
    if (((token === import14.RouterLinkWithHref) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._RouterLinkWithHref_42_3.context; }
    if (((token === import14.RouterLinkWithHref) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._RouterLinkWithHref_46_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_30_0_0:any = this._arr_60('');
    this._RouterLinkWithHref_30_3.check_routerLink(currVal_30_0_0,throwOnChange,false);
    this._RouterLinkWithHref_30_3.detectChangesInInputProps(this,this._el_30,throwOnChange);
    const currVal_42_0_0:any = this._arr_61('/memory-grid');
    this._RouterLinkWithHref_42_3.check_routerLink(currVal_42_0_0,throwOnChange,false);
    this._RouterLinkWithHref_42_3.detectChangesInInputProps(this,this._el_42,throwOnChange);
    const currVal_46_0_0:any = this._arr_62('/team');
    this._RouterLinkWithHref_46_3.check_routerLink(currVal_46_0_0,throwOnChange,false);
    this._RouterLinkWithHref_46_3.detectChangesInInputProps(this,this._el_46,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_30_3.detectChangesInHostProps(this,this._el_30,throwOnChange);
    this._RouterLinkWithHref_42_3.detectChangesInHostProps(this,this._el_42,throwOnChange);
    this._RouterLinkWithHref_46_3.detectChangesInHostProps(this,this._el_46,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_30_3.context.ngOnDestroy();
    this._RouterLinkWithHref_42_3.context.ngOnDestroy();
    this._RouterLinkWithHref_46_3.context.ngOnDestroy();
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_30_0:any = ((<any>this._RouterLinkWithHref_30_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_30_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_42_0:any = ((<any>this._RouterLinkWithHref_42_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_42_0);
  }
  private _handle_click_46_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_46_0:any = ((<any>this._RouterLinkWithHref_46_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_46_0);
  }
}
export function viewFactory_NavComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.NavComponent> {
  if ((renderType_NavComponent === (null as any))) { (renderType_NavComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_NavComponent,{})); }
  return new _View_NavComponent0(viewUtils,parentInjector,declarationEl);
}