/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/subapps/recognizer/recognizer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../app/subapps/recognizer/nn.service';
import * as import6 from '../../../../app/subapps/recognizer/drawer.service';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/constants';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/linker/query_list';
import * as import11 from '@angular/core/src/change_detection/change_detection_util';
import * as import12 from '@angular/core/src/linker/element_ref';
export class Wrapper_RecognizerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.RecognizerComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.RecognizerComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_RecognizerComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_RecognizerComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.RecognizerComponent>;
  _NNService_0_3:import5.NNService;
  _DrawerService_0_4:import6.DrawerService;
  _RecognizerComponent_0_5:Wrapper_RecognizerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RecognizerComponent_Host0,renderType_RecognizerComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'recognizer',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_RecognizerComponent0(this.viewUtils,this,0,this._el_0);
    this._NNService_0_3 = new import5.NNService();
    this._DrawerService_0_4 = new import6.DrawerService(this._NNService_0_3);
    this._RecognizerComponent_0_5 = new Wrapper_RecognizerComponent(this.renderer,this._DrawerService_0_4);
    this.compView_0.create(this._RecognizerComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._RecognizerComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.NNService) && (0 === requestNodeIndex))) { return this._NNService_0_3; }
    if (((token === import6.DrawerService) && (0 === requestNodeIndex))) { return this._DrawerService_0_4; }
    if (((token === import0.RecognizerComponent) && (0 === requestNodeIndex))) { return this._RecognizerComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RecognizerComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._RecognizerComponent_0_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._RecognizerComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const RecognizerComponentNgFactory:import9.ComponentFactory<import0.RecognizerComponent> = new import9.ComponentFactory<import0.RecognizerComponent>('recognizer',View_RecognizerComponent_Host0,import0.RecognizerComponent);
const styles_RecognizerComponent:any[] = ([] as any[]);
var renderType_RecognizerComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_RecognizerComponent,{});
export class View_RecognizerComponent0 extends import1.AppView<import0.RecognizerComponent> {
  _viewQuery_sketchpad_0:import10.QueryList<any>;
  _viewQuery_thumbnail_1:import10.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  /*private*/ _expr_44:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_RecognizerComponent0,renderType_RecognizerComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways);
    this._expr_44 = import11.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_sketchpad_0 = new import10.QueryList<any>();
    this._viewQuery_thumbnail_1 = new import10.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container-fluid','id','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Recognizing hand-written digits from MNIST dataset with Brain.js. Neural Networks live example.',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            Draw a digit in the box below and click the "recognize" button.\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-lg-9 col-md-9 col-sm-9 col-xs-9'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'canvas',new import3.InlineArray8(6,'class','img-thumbnail','height','280','width','280'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Sorry, your browser is not supported.\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','col-lg-3 col-md-3 col-sm-3 col-xs-3'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','col-lg-12 col-md-12 col-sm-12 col-xs-12'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'canvas',new import3.InlineArray8(6,'class','img-thumbnail','height','28','width','28'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Sorry, your browser is not supported.\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','col-lg-12 col-md-12 col-sm-12 col-xs-12'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,parentRenderNode,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Clear',(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,parentRenderNode,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Recognise',(null as any));
    this._text_41 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray16(12,'touchstart',(null as any),'touchmove',(null as any),'touchend',(null as any),'mousedown',(null as any),'mousemove',(null as any),'mouseup',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_36));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    this._viewQuery_sketchpad_0.reset([new import12.ElementRef(this._el_15)]);
    this.context.sketchpadEl = this._viewQuery_sketchpad_0.first;
    this._viewQuery_thumbnail_1.reset([new import12.ElementRef(this._el_23)]);
    this.context.thumbnailEl = this._viewQuery_thumbnail_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_44:any = import3.inlineInterpolate(1,'\n                    ',this.context.drawerService.result,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setText(this._text_30,currVal_44);
      this._expr_44 = currVal_44;
    }
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'touchstart')) {
      const pd_sub_0:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'touchmove')) {
      const pd_sub_1:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'touchend')) {
      const pd_sub_2:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_2 && result);
    }
    if ((eventName == 'mousedown')) {
      const pd_sub_3:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_3 && result);
    }
    if ((eventName == 'mousemove')) {
      const pd_sub_4:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_4 && result);
    }
    if ((eventName == 'mouseup')) {
      const pd_sub_5:any = ((<any>this.context.draw($event)) !== false);
      result = (pd_sub_5 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.clear()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.recognise()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}